In deze opgave classificeren afbeeldingen van bloemen uit de iris dataset met behulp van een neuraal netwerk.

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

Laad de dataset en maak een feature matrix X en een target vector y.

In [2]:
iris = sns.load_dataset('iris')

# we gebruiken .values om een Numpy array te krijgen in plaats van een Pandas DataFrame
X_iris = iris.drop('species', axis=1).values 
y_iris = iris['species'].values

iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
y_iris = y_iris.reshape(-1, 1) # maak een array van array's, dit is nodig voor de volgende stap
print(y_iris[:10])

[['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']]


Een neuraal netwerk kan niet omgaan met categorische labels zoals de namen van de planten, maar heeft getallen als uitput nodig. We hebben hier drie klassen (setosa, versicolor, virginica) daarom maken we een target vector met per label drie waarden. Een 1 voor de eerste waarde correspondeert met 'setosa', een 1 voor de 2e waade met 'versicolor' en een 1 voor de derde waarde met 'virginica'.

Doe dit met behulp van het `OneHotEncoder` object uit sklearn.

In [4]:
# Replaces species with numbers
enc = OneHotEncoder()
y_iris = enc.fit_transform(y_iris).toarray()
print(y_iris)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

We hebben de data nu in een geschikt formaat. Splits de data in training en test data.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

Maak een eenvoudig neuraal netwerk met 3 lagen, waarin elke neuron in een laag met elk neuron in de vorige laag verbonden is ('Dense'). 
Voeg voor de eeste laag een parameter `input_shape` toe die aangeeft hoeveel features een element in 'X' heeft.
Het aantal neuronen in de laaste laag is gelijk aan het aantal waarden in een label in `y`. 

In [6]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

#voeg lagen toe met model.add()
model.add(Dense(4, input_shape=(4,), activation='relu'))
model.add(Dense(5, activation='softmax'))
model.add(Dense(3, activation='softmax'))


Compileer en bekijk het netwerk door onderstaande code te runnen.

In [7]:
from keras.optimizers.legacy import Adam

model.compile(Adam(learning_rate=0.01),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 20        
                                                                 
 dense_1 (Dense)             (None, 5)                 25        
                                                                 
 dense_2 (Dense)             (None, 3)                 18        
                                                                 
Total params: 63 (252.00 Byte)
Trainable params: 63 (252.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Nu kunnen we ons model trainen met behulp van de `fit` methode.

In [8]:
model.fit(X_train, y_train, epochs = 40, batch_size = 5)

Epoch 1/40
24/24 [==============================] - 0s 845us/step - loss: 1.0560 - accuracy: 0.4083
Epoch 2/40
24/24 [==============================] - 0s 641us/step - loss: 0.9543 - accuracy: 0.5167
Epoch 3/40
24/24 [==============================] - 0s 589us/step - loss: 0.8136 - accuracy: 0.7417
Epoch 4/40
24/24 [==============================] - 0s 557us/step - loss: 0.6913 - accuracy: 0.7917
Epoch 5/40
24/24 [==============================] - 0s 559us/step - loss: 0.5915 - accuracy: 0.9083
Epoch 6/40
24/24 [==============================] - 0s 515us/step - loss: 0.5057 - accuracy: 0.8833
Epoch 7/40
24/24 [==============================] - 0s 565us/step - loss: 0.4288 - accuracy: 0.9250
Epoch 8/40
24/24 [==============================] - 0s 566us/step - loss: 0.3639 - accuracy: 0.9250
Epoch 9/40
24/24 [==============================] - 0s 547us/step - loss: 0.2953 - accuracy: 0.9750
Epoch 10/40
24/24 [==============================] - 0s 533us/step - loss: 0.2408 - accuracy: 0.9833

Met `model_evaluate` kunnen we bepalen hoe goed het model werkt op de test data.

In [9]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(test_acc)

1/1 [==============================] - 0s 94ms/step - loss: 0.0810 - accuracy: 0.9667
0.9666666388511658


#### Experimenteer met bovenstaand model. Wat gebeurt er als je meer lagen toevoegt of een laag weghaalt of het aantal neuronen in een laag verandert? 

Met 3 lagen, geeft hij de eerste keer een accuracy van 63% Als ik hem opnieuw run, dan gaat de acuracy omhoog naar 93%. Soms geeft het een accuracy van 100%

Ik heb de 2e laag weggehaald, dus het model heeft nu de unput laag en een output laag, dus geen hidden layers.
Als ik het model train, dan geeft hij een accuracy rond 80-90%. Als ik de code opnieuw run, krijg ik andere waarden, soms 95% en soms 100% acuracy.

Wat mij vooral opvalt is dat het elke keer een ander resultaat geeft, soms geef het een laag resultaat zoals 30%, en soms 100%. Persoonlijk weet ik niet waaraan dit ligt.

#### Probeer ook eens andere activatiefuncties dan `relu`, zoals `tanh` of `sigmoid`.

Persoonlijk zie ik geen verschil in de resultaten, het geeft weer elke keer een andere accuracy. tussen 60% en 100%

#### Welke invloed heeft het aantal epochs?
Als ik de epochs van 25 naar 40 zet, gaat de accuracy zeer omhoog. Nu is het altijd tussen 95-100%. Met elke run die ik doe blijft het resultaat ongeveer hetzelfde en blijt stabiel.

We kunnen dezelfde aanpak gebruiken voor andere data, bijvoorbeeld voor het herkennen van cijfers. We gebruiken de `MNist` dataset die bestaat uit plaatjes van cijfers. Ieder plaatje bestaat uit 28 x 28 pixels.

In [10]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

import warnings
warnings.filterwarnings('ignore')

In [11]:
train_images.shape

(60000, 28, 28)

In [12]:
len(train_labels)

60000

In [13]:
print(train_labels)

[5 0 4 ... 5 6 8]


Een eenvoudig neuraal netwerk heeft een array van inputwaarden nodig i.p.v. een 2D afbeelding.
We maken van de inputs (waarden tussen 0 en 255) getallen tussen 0 en 1.

In [14]:
train_images = train_images.reshape((60000, 28 * 28)) # lijst van waarden i.p.v. 2D afbeelding
train_images = train_images.astype('float32') / 255 # getallen tussen 0 en 1

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

Voor elk label (een cijfer) maken we een array met 10 waarden: 9 nullen en een één, waarbij de positie van de één aangeeft om welk cijfer het gaat (One hot encoding). Dit keer gebruiken we hiervoor de `keras` functie `to_categorical`.

In [15]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


Maak nu een neuraal netwerk met twee lagen, een eerste laag met 512 neuronen en een output laag met 10 neuronen. Geef bij de eerste laag aan hoeveel inputs er zijn en wat de activatiefunctie is. De output laag heeft een `softmax` activatiefunctie.

In [16]:
# Neural Network with 2 layers
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(28 * 28,))) # 28*28 = 784, because of the size of the images
model.add(Dense(10, activation='softmax'))

compileer het netwerk.

In [17]:
# Compile the model
model.compile(Adam(learning_rate=0.01),'categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 512)               401920    
                                                                 
 dense_4 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407050 (1.55 MB)
Trainable params: 407050 (1.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


train het netwerk 5 epochs met een batch_size van 128.

In [18]:
# Train the model
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5


469/469 [==============================] - 1s 2ms/step - loss: 0.2113 - accuracy: 0.9366
Epoch 2/5
469/469 [==============================] - 2s 5ms/step - loss: 0.1099 - accuracy: 0.9670
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0957 - accuracy: 0.9719
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0787 - accuracy: 0.9771
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0726 - accuracy: 0.9797


Evalueer het netwerk op de test set.

In [19]:
# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

313/313 [==============================] - 0s 774us/step - loss: 0.1391 - accuracy: 0.9688
0.9688000082969666


In mijn eerste model heb ik de volgende gegevens: 1e layer met 784 inputs en 512 neurons en activation relu. Ik gebruik 784 input omdat de afbeelding 28 * 28 is, dus 784 pixels in totaal. De output layer is 10 met activation softmax.

Wat mij opvalt is dat het een hoge accuracy heeft van ±98%. Wel is het model 'slomer' dan het iris model. Maar dat komt omdat je veel meer verbindingen hebt tussen de neurons, en natuurlijk een hele grote input hebt.

Experimenteer met verschillende netwerken. Varieer het aantal lagen, het aantal neuronen, de activatiefunties en het aantal epochs.

In [20]:
# Model with extra layer
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(Adam(learning_rate=0.01),'categorical_crossentropy',metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=5, batch_size=128)

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 0.2643 - accuracy: 0.9255
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.1383 - accuracy: 0.9589
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.1154 - accuracy: 0.9666
Epoch 4/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1035 - accuracy: 0.9710
Epoch 5/5
313/313 [==============================] - 0s 983us/step - loss: 0.1588 - accuracy: 0.9621
0.9621000289916992


Met een extra laag is de accuracy om laag gegaan met ±2% Wat ook opvalt is dat het langer duurt per epoch nu dat er een extra laag in zit.


In [21]:
# Model with more epochs but same amount of layers
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(Adam(learning_rate=0.01),'categorical_crossentropy',metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, batch_size=128)

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

Epoch 1/10
469/469 [==============================] - 2s 4ms/step - loss: 0.2056 - accuracy: 0.9372
Epoch 2/10
469/469 [==============================] - 2s 4ms/step - loss: 0.1145 - accuracy: 0.9656
Epoch 3/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0882 - accuracy: 0.9738
Epoch 4/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0795 - accuracy: 0.9772
Epoch 5/10
469/469 [==============================] - 1s 3ms/step - loss: 0.0678 - accuracy: 0.9808
Epoch 6/10
469/469 [==============================] - 1s 3ms/step - loss: 0.0641 - accuracy: 0.9827
Epoch 7/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0602 - accuracy: 0.9833
Epoch 8/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0529 - accuracy: 0.9858
Epoch 9/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0557 - accuracy: 0.9855
Epoch 10/10
313/313 [==============================] - 0s 1ms/step - loss: 0.1693 - accuracy: 0.9730

Nu is de accuracy iets omhoog gegaan, met ±1%. Dit komt omdat er meer epochs zijn en het model dus langer getraind wordt en de gewichten van het model aangepast worden.

In [26]:
# Model with more epochs and extra layer
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(Adam(learning_rate=0.01),'categorical_crossentropy',metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, batch_size=128)

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

Epoch 1/10
469/469 [==============================] - 2s 4ms/step - loss: 0.2590 - accuracy: 0.9246
Epoch 2/10
469/469 [==============================] - 2s 5ms/step - loss: 0.1360 - accuracy: 0.9602
Epoch 3/10
469/469 [==============================] - 4s 8ms/step - loss: 0.1090 - accuracy: 0.9689
Epoch 4/10
469/469 [==============================] - 3s 6ms/step - loss: 0.1080 - accuracy: 0.9700
Epoch 5/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0924 - accuracy: 0.9744
Epoch 6/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0888 - accuracy: 0.9761
Epoch 7/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0823 - accuracy: 0.9774
Epoch 8/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0768 - accuracy: 0.9796
Epoch 9/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0695 - accuracy: 0.9811
Epoch 10/10
313/313 [==============================] - 0s 928us/step - loss: 0.1553 - accuracy: 0.97

Het zelfde geld voor dit model.

In [29]:
# Model with even more epochs and more layers
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(512, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(Adam(learning_rate=0.01),'categorical_crossentropy',metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=15, batch_size=128)

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

Epoch 1/15
469/469 [==============================] - 4s 9ms/step - loss: 0.3237 - accuracy: 0.9108
Epoch 2/15
469/469 [==============================] - 4s 9ms/step - loss: 0.1609 - accuracy: 0.9554
Epoch 3/15
469/469 [==============================] - 4s 9ms/step - loss: 0.1393 - accuracy: 0.9629
Epoch 4/15
469/469 [==============================] - 4s 9ms/step - loss: 0.1253 - accuracy: 0.9658
Epoch 5/15
469/469 [==============================] - 4s 9ms/step - loss: 0.1160 - accuracy: 0.9685
Epoch 6/15
469/469 [==============================] - 4s 9ms/step - loss: 0.1148 - accuracy: 0.9696
Epoch 7/15
469/469 [==============================] - 4s 9ms/step - loss: 0.0954 - accuracy: 0.9748
Epoch 8/15
469/469 [==============================] - 4s 9ms/step - loss: 0.1036 - accuracy: 0.9724
Epoch 9/15
469/469 [==============================] - 4s 9ms/step - loss: 0.0939 - accuracy: 0.9753
Epoch 10/15
469/469 [==============================] - 4s 9ms/step - loss: 0.0943 - accuracy: 0.9754

In dit model heb ik 2 layers toegevoegd en meer epochs. Dit duurde veel langer, omdat er dus meer lagen zijn en meer epochs. Wat ook opvalt is dat de accuracy met ±1% omlaag gaat.

Dit kan komen door verschillende dingen:
1. Doordat we zolang trainen op 1 model, betekend dat het model te erg gewend is aan de train data. Als je het model dan gebruikt op de test data, dan performed hij dus slechter omdat het niet lijkt op de train data. Dit noem je Overfitting
2. Misschien is ons model te complex voor ons plobleem. Door extra lagen toe te voegen wordt het model zeer complex. Daarom kan het model minder goed scoren op een relatief simpel probleem.